import pygame

ENEMY_REACHED_END = pygame.USEREVENT + 1
PLAYER_GAME_OVER = pygame.USEREVENT + 2
PLAYER_VICTORY = pygame.USEREVENT + 3
ENEMY_KILLED = pygame.USEREVENT + 4
PLAYER_DAMAGED = pygame.USEREVENT + 5
PLAYER_INVENTORY_SELECTED = pygame.USEREVENT + 6
PLAYER_EXIT = pygame.USEREVENT + 7
STAGE_WAVE_END = pygame.USEREVENT + 8